version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
      - POSTGRES_DB=stats
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --advertise-kafka-addr
      - redpanda:9092
    ports:
      - "9092:9092"   # Kafka
      - "9644:9644"   # Admin API

  victoria:
    image: victoriametrics/victoria-metrics:latest
    ports:
      - "8428:8428"   # HTTP API
    volumes:
      - vm-data:/storage

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - victoria

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    environment:
      - KAFKA_BROKERS=redpanda:9092
    ports:
      - "8080:8080"
    depends_on:
      - redpanda

volumes:
  postgres-data:
  vm-data: