version: "3.9"
services:
  # postgres:
  #   image: postgres:16
  #   environment:
  #     - POSTGRES_USER=stats
  #     - POSTGRES_PASSWORD=stats
  #     - POSTGRES_DB=stats
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --mode
      - dev-container          # базовый пресет
      - --smp
      - "1"
      # ↓ 2 строки решают проблему «127.0.0.1»
      - --kafka-addr           # где брокер СЛУШАЕТ
      - internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr # какие адреса ОТДАЁТ клиентам
      - internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092"          # Kafka для приложений на хосте
      - "9644:9644"            # Admin API
    networks: [default]

  console:
    image: docker.redpanda.com/redpandadata/console:latest
    depends_on: [redpanda]
    environment:
      KAFKA_BROKERS: redpanda:9092       # внутри сети «docker»
      REDPANDA_ADMIN_URLS: http://redpanda:9644
    ports:
      - "8080:8080"
    networks: [default]

  victoria:
    image: victoriametrics/victoria-metrics:latest
    ports:
      - "8428:8428"   # HTTP API
    volumes:
      - vm-data:/storage

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - victoria

  # gateway:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.gateway
  #   environment:
  #     - KAFKA_BROKERS=redpanda:9092
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - redpanda

volumes:
  postgres-data:
  vm-data: